# Testing Pytorch Functionality

In [1]:
import numpy as np
import torch

In [5]:
x = torch.randn(3, 4)
print(x)
batch, dim = x.shape
print(batch)
print(dim)

tensor([[-0.0412,  0.1623,  0.4948,  1.4074],
        [-0.2691,  0.5808,  0.3340,  1.0805],
        [-0.2290, -0.1937, -0.3674, -0.7551]])
3
4


In [10]:
vector = torch.randn(4)
print(vector)
print((vector**2).sum())

tensor([-1.0999, -0.6286,  1.7208, -0.6007])
tensor(4.9271)


In [ ]:
# Broadcasting pitfalls
vec1 = torch.arange(5)
print(vec1)
print(vec1.shape)

# Note that the -1 tells torch to infer the size of the dimension
# Since we've specified the size of the second dimension as 1,
# the -1 will become 5 (since there are a total of 5 elements)
vec2 = torch.arange(5).reshape(-1, 1)
print(vec2)
print(vec2.shape)

# Squeeze removes dimensions of size 1
# The -1 argument tells torch to remove all instances, but you can
# instead specify specific dimensions to look over for removal
# Note that we could have alternatively used vec2_squeezed = vec2.reshape(5)
vec2_squeezed = vec2.squeeze(-1)
print(vec2_squeezed)
print(vec2_squeezed.shape)

print(vec1 + vec2)
print(vec1 + vec2_squeezed)

tensor([0, 1, 2, 3, 4])
torch.Size([5])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([5, 1])
tensor([0, 1, 2, 3, 4])
torch.Size([5])
tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]])
tensor([0, 2, 4, 6, 8])
